=== jessealama/argo/tests/validation/json-schema.org/calendar/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A representation of an event",
    "type": "object",
    "required": [ "dtstart", "summary" ],
    "properties": {
        "dtstart": {
            "format": "date-time",
            "type": "string",
            "description": "Event starting time"
        },
        "dtend": {
            "format": "date-time",
            "type": "string",
            "description": "Event ending time"
        },
        "summary": { "type": "string" },
        "location": { "type": "string" },
        "url": { "type": "string", "format": "uri" },
        "duration": {
            "type": "string",
            "description": "Event duration"
        },
        "rdate": {
            "format": "date-time",
            "type": "string",
            "description": "Recurrence date"
        },
        "rrule": {
            "type": "string",
            "description": "Recurrence rule"
        },
        "category": { "type": "string" },
        "description": { "type": "string" },
        "geo": { "$ref": "https://json-schema.org/learn/examples/geographical-location.schema.json" }
    }
}

=== jessealama/argo/argo/tests/validation/json-schema.org/calendar/positive/full.json
{
    "dtstart": "2016-05-24T15:30:00+01:00",
    "dtend": "2016-05-24T18:30:00+01:00",
    "summary": "great party",
    "location": "Grüne Brücke",
    "url": "https://mainz.de",
    "duration": "3 hours",
    "rdate": "2017-05-24T15:30:00+01:00",
    "rrule": "every year",
    "category": "parties",
    "description": "hanging out",
    "geo": {
	"latitude": 4,
	"longitude": 56
    }
}
